import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Componants/Navbar/Navbar";
import Footer from "@/Componants/Footer/Footer";
import AuthProvider from "@/Context/AuthProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Coffee Garden",
  description: "Generated by Coffee Garden",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
          <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  );
}
